### ISSUE TITLE
setTextureFromArray does not bind texture

### ISSUE THREAD

**Issue by pnp2084** [greggman/tdl#8]
setTextureFromArray() takes a texture parameter _tex_ but does not call gl.bindTexture() (or even use the parameter at all).  As a result the last bound texture gets modified instead of the passed in texture.

**Comment by greggman** [comment]
Doh! How did it ever work :(   Fixing

**Comment by greggman** [comment]
pushed version 0.0.33 with that fix. Please check.

**Comment by greggman** [comment]
Oh wait, I was thinking twgl not tdl. Sorry. I haven't uploaded a fix for tdl

**Comment by pnp2084** [comment]
Excellent, fixed, and thanks! The bug was in twgl, I posted to the wrong project. (Doh)

BTW, thanks for the library--it made it easy to get to the real work (some shaders) instead of having to wade through the the OpenGL API.
